/**
 * RoboScan API
 * RoboScan API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CameraSetting { 
    /**
     * Camera setting value
     */
    value: string;
    /**
     * True if it is the currently active setting
     */
    active?: boolean;
    /**
     * True if it is the setting used last time
     */
    last_used?: boolean;
}

