/**
 * PiScanner API
 * PiScanner API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface SessionDetails { 
    /**
     * Session ID
     */
    id: number;
    /**
     * True if a scan is on-going
     */
    is_scanning: boolean;
}